#!/bin/bash
.PHONY: mrproper clean

SRC= src
BIN= bin
LIB= lib
OBJ= obj
INC= include
FOLDERS = $(SRC) $(BIN) $(LIB) $(OBJ) $(INC)


CC = g++
AR = ar
CCFLAGS = -Wall -pedantic -g
LDFLAGS = -L./$(LIB)
LDLIBS = -lconecta
IFLAGS = -I
LIBFLAGS = rvs

SOURCESMAIN = $(SRC)/ConectaN.cpp
SOURCESLIB= $(SRC)/matriz.cpp $(SRC)/tablero.cpp $(SRC)/jugador.cpp $(SRC)/plastico.cpp
OBJECTS = $(SOURCESMAIN:$(SRC)/%.cpp=$(OBJ)/%.o) $(SOURCESLIB:$(SRC)/%.cpp=$(OBJ)/%.o)
EXECUTABLES = $(SOURCESMAIN:$(SRC)/%.cpp=./% )
LIBNAME = $(LIB)/libconecta.a


all : ./$(FOLDERS) $(OBJECTS) $(EXECUTABLES)  clean ~/Documentos/ConectaN

./% : $(OBJ)/%.o $(LIBNAME)
	$(CC) $(CCFLAGS) $(IFLAGS) $(INC) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(LIBNAME) : $(SOURCESLIB:$(SRC)/%.cpp=$(OBJ)/%.o)  $(SOURCESLIB:$(SRC)/%.cpp=$(INC)/%.h)
	$(AR) $(LIBFLAGS) $(LIBNAME) $^

$(OBJ)/%.o : $(SRC)/%.cpp
	$(CC) $(CCFLAGS) $(IFLAGS) $(INC) -c $^ -o $@

~/Documentos/ConectaN :
	mkdir ~/Documentos/ConectaN 2> /dev/null

./$(FOLDERS) :
	mkdir $(FOLDERS) 2> /dev/null


clean :
	rm $(OBJ)/*.o

mrproper :
	rm $(BIN)/* 2> /dev/null
	rm $(LIB)/* 2> /dev/null
